x-restart-policy: &restart_policy
  restart: on-failure:3

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s
  timeout: 1m
  start_period: 10s
  retries: 3

services:
  redis:
    container_name: redis
    image: redis
    <<: *restart_policy
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: redis-cli ping
      <<: *healthcheck_defaults

  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight
    <<: *restart_policy
    profiles:
      - redis-insight
    ports:
      - "5540:5540"
    healthcheck:
      test: wget --spider http://127.0.0.1:5540/api/health
      <<: *healthcheck_defaults

volumes:
  redis-data:
