image:
  repository: host.minikube.internal:5000/ya-arch-sprint-2-project-api

settings:
  mongodb:
    dbName: example_db
    writeConcern: 1

externalSecrets:
  enabled: true
  provider:
    vault:
      server: http://host.minikube.internal:8200
      path: secret
      auth:
        userPass:
          path: userpass
          username: admin
          secretRef:
            name: api-vault-password
            key: password

knative:
  enabled: true

autoscaling:
  enabled: false
