services:
  api:
    depends_on:
      mongodb:
        condition: service_healthy
    image: ya-arch-sprint-2-project-api:0.1.0-distroless
    build:
      context: ../../api
      dockerfile: distroless.Dockerfile
    restart: on-failure:3
    profiles:
      - api
    ports:
      - "8080:8080"
    environment:
      MONGODB__URL: mongodb://mongodb
      MONGODB__DB_NAME: somedb
    healthcheck:
      test: ["CMD", "python", "-m", "api.utils.healthcheck"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
