services:
  api:
    container_name: api
    depends_on:
      mongos-router:
        condition: service_healthy
    image: ya-arch-sprint-2-project/api
    build:
      context: ../../api
    restart: on-failure:3
    profiles:
      - api
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: mongodb://mongos-router
      MONGODB_DATABASE_NAME: somedb
    healthcheck:
      test: curl --fail http://localhost:8080/livez
      interval: 10s
      timeout: 1m
      start_period: 10s
      retries: 3
