services:
  api:
    depends_on:
      mongodb:
        condition: service_healthy
    image: ya-arch-sprint-2-project/api
    build:
      context: ../../api
    restart: on-failure:3
    ports:
      - "8080:8080"
    environment:
      MONGODB__URL: mongodb://mongodb
      MONGODB__DATABASE_NAME: somedb
    healthcheck:
      test: curl --fail http://localhost:8080/livez
      interval: 10s
      timeout: 1m
      start_period: 10s
      retries: 3
