services:
  api:
    depends_on:
      mongodb:
        condition: service_healthy
    image: ya-arch-sprint-2-project-api:0.1.0-distroless
    pull_policy: never
    build:
      context: ../../api
      target: distroless
    restart: on-failure:3
    profiles:
      - api
    ports:
      - "8080:8080"
    environment:
      MONGODB__URL: mongodb://mongodb
      MONGODB__DB_NAME: example_db
    healthcheck:
      test: [CMD, python, -m, api.utils.healthcheck]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
