x-restart-policy: &restart_policy
  restart: on-failure:3

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s
  timeout: 1m
  start_period: 10s
  retries: 3

services:
  mongodb:
    container_name: mongodb
    image: mongo
    <<: *restart_policy
    profiles:
      - mongodb
      - mongo-express
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ../scripts/mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      <<: *healthcheck_defaults

  mongo-express:
    container_name: mongo-express
    depends_on:
      mongodb:
        condition: service_healthy
    image: mongo-express
    <<: *restart_policy
    profiles:
      - mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb
      ME_CONFIG_BASICAUTH: false
    healthcheck:
      # does not resolve localhost
      test: wget --spider http://127.0.0.1:8081
      <<: *healthcheck_defaults

volumes:
  mongodb-data:
