services:
  api:
    depends_on:
      redis:
        condition: service_healthy
        required: false
      redis-cluster-init:
        condition: service_completed_successfully
        required: false
    environment:
      REDIS__URL: redis://redis
#      REDIS__URL: redis://ya-arch-sprint-2-project-redis-cluster-1
#      REDIS__IS_CLUSTER: true
