x-restart-policy: &restart_policy
  restart: on-failure:3

x-healthcheck-defaults: &healthcheck_defaults
  interval: 10s
  timeout: 1m
  start_period: 10s
  retries: 3

services:
  vault:
    container_name: vault
    depends_on:
      consul:
        condition: service_healthy
    image: hashicorp/vault
    <<: *restart_policy
    profiles:
      - vault
    ports:
      - "8200:8200"
    volumes:
      - ./configs/vault.hcl:/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    # override default dev mode, no need for `-config`: https://github.com/hashicorp/docker-vault/issues/109
    command: [server]
    healthcheck:
      test: wget --spider http://127.0.0.1:8200
      <<: *healthcheck_defaults

  vault-init:
    container_name: vault-init
    depends_on:
      vault:
        condition: service_started
    image: hashicorp/vault
    <<: *restart_policy
    profiles:
      - vault
    volumes:
      - ./scripts/vault-init.sh:/vault-init.sh
    environment:
      ADMIN_PASSWORD: password
      MONGODB__URL: mongodb://host.minikube.internal
      REDIS__URL: redis://host.minikube.internal
    command: [/vault-init.sh]
