replicaCount: 1

image:
  repository:
  tag: 0.1.0-distroless
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

mongodb:
  url: ""
  dbName:

redis:
  url: ""
  isCluster:

knative:
  enabled: false
  metric: rps
  target: 50
  maxScale: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage:

externalSecrets:
  enabled: false
  provider:

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
