replicaCount: 2

image:
  repository:
  tag: 0.1.0-distroless
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

settings:
  mongodb:
    url: ''
    dbName:
    writeConcern:
  redis:
    url: ''
    isCluster:
  dummy:

knative:
  enabled: false
  metric: rps
  target: 50
  maxScale: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage:

externalSecrets:
  enabled: false
  provider:

resources:
  requests:
    memory: 64Mi
    cpu: 50m
    ephemeral-storage: 100Mi
  limits:
    memory: 256Mi
    cpu: 250m
    ephemeral-storage: 500Mi

networkPolicy:
  enabled: false

serviceAccount:
  create: true
  name:

ingress:
  enabled: false
  className:
  annotations: {}

  hosts:
    - host: api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
