apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  UVICORN_PORT: "{{ .Values.service.port }}"
  MONGODB__DB_NAME: "{{ .Values.settings.mongodb.dbName }}"
  MONGODB__WRITE_CONCERN: "{{ .Values.settings.mongodb.writeConcern }}"
  REDIS__IS_CLUSTER: "{{ .Values.settings.redis.isCluster }}"
  DUMMY: "{{ .Values.settings.dummy}}"
