apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  UVICORN_PORT: "{{ .Values.service.port }}"
  MONGODB__DB_NAME: "{{ .Values.mongodb.dbName }}"
  REDIS__IS_CLUSTER: "{{ .Values.redis.isCluster }}"
