{{- if not .Values.knative.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
      annotations:
        {{- include "spec.annotations" . | nindent 8 }}
    spec:
      {{- include "spec.topologySpreadConstraints" . | nindent 6 }}
      {{- include "spec.podSecurity" . | nindent 6 }}
      {{- include "spec.containers" . | nindent 6 }}
{{- end }}
