{{- if .Values.knative.enabled -}}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
      annotations:
        {{- include "api.template.annotations" . | nindent 8 }}
        autoscaling.knative.dev/max-scale: {{ .Values.knative.maxScale | quote }}
        autoscaling.knative.dev/metric: {{ .Values.knative.metric }}
        autoscaling.knative.dev/target: {{ .Values.knative.target | quote }}
        autoscaling.knative.dev/window: 30s
    spec:
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      timeoutSeconds: 20
      {{- include "api.containers" . | nindent 6 }}
{{- end }}
