{{- if not .Values.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB__URL: {{ .Values.settings.mongodb.url | b64enc | quote }}
  REDIS__URL: {{ .Values.settings.redis.url | b64enc | quote }}
{{- end }}
