{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ include "api.fullname" . }}-vault"
spec:
  provider:
    {{- toYaml .Values.externalSecrets.provider | nindent 4 }}
{{- end}}
