{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ include "api.fullname" . }}-vault"
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.externalSecrets.provider | nindent 4 }}
{{- end}}
