{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ include "api.fullname" . }}-vault"
    kind: SecretStore
  target:
    name: {{ include "api.fullname" . }}
  data:
    - secretKey: MONGODB__URL
      remoteRef:
        key: api/mongodb
        property: url
    - secretKey: REDIS__URL
      remoteRef:
        key: api/redis
        property: url
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB__URL: {{ .Values.settings.mongodb.url | b64enc | quote }}
  REDIS__URL: {{ .Values.settings.redis.url | b64enc | quote }}
{{- end }}
