x-mongodb-shard-base: &mongodb_shard_base
  image: mongo
  restart: on-failure:3
  healthcheck:
    test: echo 'db.runCommand("ping").ok' | mongosh localhost:27018/test --quiet
    interval: 10s
    timeout: 1m
    start_period: 10s
    retries: 3

services:
  mongodb-shard-1-2:
    container_name: mongodb-shard-1-2
    <<: *mongodb_shard_base
    volumes:
      - mongodb-shard-1-2-data:/data/db
    command: [--shardsvr, --replSet, shard-1, --bind_ip_all]

  mongodb-shard-1-3:
    container_name: mongodb-shard-1-3
    <<: *mongodb_shard_base
    volumes:
      - mongodb-shard-1-3-data:/data/db
    command: [--shardsvr, --replSet, shard-1, --bind_ip_all]

  mongodb-shard-2-2:
    container_name: mongodb-shard-2-2
    <<: *mongodb_shard_base
    volumes:
      - mongodb-shard-2-2-data:/data/db
    command: [--shardsvr, --replSet, shard-2, --bind_ip_all]

  mongodb-shard-2-3:
    container_name: mongodb-shard-2-3
    <<: *mongodb_shard_base
    volumes:
      - mongodb-shard-2-3-data:/data/db
    command: [--shardsvr, --replSet, shard-2, --bind_ip_all]

volumes:
  mongodb-shard-1-2-data:
  mongodb-shard-1-3-data:
  mongodb-shard-2-2-data:
  mongodb-shard-2-3-data:
